[env:esp32dev]
platform      = espressif32
board         = esp32dev
board_build.partitions = huge_app.csv
framework     = arduino
upload_port   = COM4
monitor_port  = COM4
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=0
    "-Wl,-z,muldefs"

lib_deps =
    olikraus/U8g2@^2.35.0
    h2zero/NimBLE-Arduino@^2.5.0
    nrf24/RF24@^1.6.0
    crankyoldgit/IRremoteESP8266@^2.8.6
    adafruit/Adafruit BusIO@^1.16.0

lib_ignore =
    Adafruit PN532

lib_extra_dirs =
    c:/Users/56/Documents/Arduino/libraries
